apiVersion: runtime.agentic-layer.ai/v1alpha1
kind: AgentGateway
metadata:
  labels:
    app.kubernetes.io/name: agent-gateway-krakend-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-gateway
  namespace: showcase-news
spec:
  agentGatewayClassName: krakend  # Optional: specify controller responsibility
  replicas: 1 # Optional
  timeout: "30000ms"  # Request timeout (optional, default: 60000ms)
